config/routes.rb
Rails.application.routes.draw do

  resources :candidaturas do
    collection do
      get 'selecionar_turma'
      get 'urna'
      post 'registrar_voto'
    end
  end

  resources :turmas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/candidatura.rb
class Candidatura < ApplicationRecord
  belongs_to :turma
  has_one_attached :foto_lider
  has_one_attached :foto_vice
  attribute :votos, :integer, default: 0
end

app/models/turma.rb
class Turma < ApplicationRecord
  has_many :candidaturas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/candidaturas_controller.rb
class CandidaturasController < ApplicationController
  before_action :set_candidatura, only: %i[show edit update]


  def index
    @candidaturas = Candidatura.all
  end

  def show
  end

  def new
    @candidatura = Candidatura.new
  end

  def edit
  end

  def create
    @candidatura = Candidatura.new(candidatura_params)

    respond_to do |format|
      if @candidatura.save
        format.html { redirect_to @candidatura, notice: "Candidatura criada com sucesso." }
        format.json { render :show, status: :created, location: @candidatura }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @candidatura.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @candidatura.update(candidatura_params)
        format.html { redirect_to @candidatura, notice: "Candidatura atualizada com sucesso." }
        format.json { render :show, status: :ok, location: @candidatura }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @candidatura.errors, status: :unprocessable_entity }
      end
    end
  end


  def selecionar_turma
    @turmas = Turma.all
  end

  def listar_candidatos
    @turma = Turma.find(params[:turma_id])
    @candidaturas = Candidatura.where(turma_id: @turma.id)

    if @candidaturas.empty?
      redirect_to urna_candidaturas_path, alert: "Nenhum candidato encontrado para esta turma."
    end
  end

  def registrar_voto
    if params[:voto_em_branco] == "true"
      @turma = Turma.find(params[:turma_id])
      @turma.increment!(:votos_em_branco)
      redirect_to urna_candidaturas_path, notice: "Voto em branco registrado com sucesso!"
    else
      @candidatura = Candidatura.find(params[:candidatura_id])
      @candidatura.increment!(:votos)
      redirect_to urna_candidaturas_path, notice: "Voto registrado com sucesso!"
    end
  end





  def urna
    @turma = Turma.find(params[:turma_id])
    @candidaturas = Candidatura.where(turma_id: @turma.id)

    if @candidaturas.empty?
      flash[:alert] = "Não há candidatos para esta turma."
      redirect_to selecionar_turma_candidaturas_path
    end
  end

  def registrar_voto
    if params[:candidatura_id].blank?
      # Voto em branco
      turma = Turma.find(params[:turma_id])
      turma.increment!(:votos_em_branco)
      redirect_to selecionar_turma_candidaturas_path, notice: "Voto em branco registrado com sucesso!"
    else
      # Voto em candidato
      @candidatura = Candidatura.find(params[:candidatura_id])
      @candidatura.increment!(:votos)
      redirect_to selecionar_turma_candidaturas_path, notice: "Voto registrado com sucesso!"
    end
  end


  private

  def set_candidatura
    @candidatura = Candidatura.find(params[:id])
  end

  def candidatura_params
    params.require(:candidatura).permit(:nome_candidato, :nome_urna, :turma_id, :vice_lider, :nome_urna_vice, :foto_lider, :foto_vice)
  end
end

app/controllers/turmas_controller.rb
class TurmasController < ApplicationController
  before_action :set_turma, only: %i[ show edit update destroy ]

  # GET /turmas or /turmas.json
  def index
    @turmas = Turma.all
  end

  # GET /turmas/1 or /turmas/1.json
  def show
  end

  # GET /turmas/new
  def new
    @turma = Turma.new
  end

  # GET /turmas/1/edit
  def edit
  end

  # POST /turmas or /turmas.json
  def create
    @turma = Turma.new(turma_params)

    respond_to do |format|
      if @turma.save
        format.html { redirect_to @turma, notice: "Turma was successfully created." }
        format.json { render :show, status: :created, location: @turma }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turmas/1 or /turmas/1.json
  def update
    respond_to do |format|
      if @turma.update(turma_params)
        format.html { redirect_to @turma, notice: "Turma was successfully updated." }
        format.json { render :show, status: :ok, location: @turma }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turmas/1 or /turmas/1.json
  def destroy
    @turma.destroy!

    respond_to do |format|
      format.html { redirect_to turmas_path, status: :see_other, notice: "Turma was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turma
      @turma = Turma.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def turma_params
      params.require(:turma).permit(:nome)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidaturas_helper.rb
module CandidaturasHelper
end

app/helpers/turmas_helper.rb
module TurmasHelper
end

app/views/candidaturas/_candidatura.html.erb
<div id="<%= dom_id candidatura %>">
  <p>
    <strong>Nome candidato:</strong>
    <%= candidatura.nome_candidato %>
  </p>

  <p>
    <strong>Nome urna:</strong>
    <%= candidatura.nome_urna %>
  </p>

  <p>
    <strong>Turma:</strong>
    <%= candidatura.turma_id %>
  </p>

  <p>
    <strong>Vice líder:</strong>
    <%= candidatura.vice_lider %>
  </p>

  <p>
    <strong>Nome urna vice:</strong>
    <%= candidatura.nome_urna_vice %>
  </p>

  <p>
    <strong>Foto líder:</strong>
    <%= image_tag candidatura.foto_lider if candidatura.foto_lider.present? %>
  </p>

  <p>
    <strong>Foto vice:</strong>
    <%= image_tag candidatura.foto_vice if candidatura.foto_vice.present? %>
  </p>
</div>

app/views/candidaturas/_form.html.erb
<%= form_with(model: candidatura, local: true) do |form| %>
  <% if candidatura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(candidatura.errors.count, "error") %> proibiu esta candidatura de ser salva:</h2>
      <ul>
        <% candidatura.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nome_candidato %>
    <%= form.text_field :nome_candidato, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :nome_urna %>
    <%= form.text_field :nome_urna, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :turma_id %>
    <%= form.collection_select :turma_id, Turma.all, :id, :nome, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :vice_lider %>
    <%= form.text_field :vice_lider, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :nome_urna_vice %>
    <%= form.text_field :nome_urna_vice, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :foto_lider %>
    <%= form.file_field :foto_lider, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :foto_vice %>
    <%= form.file_field :foto_vice, class: "form-control" %>
  </div>

  <div class="actions mt-3">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/candidaturas/edit.html.erb
<% content_for :title, "Editing candidatura" %>

<h1>Editing candidatura</h1>

<%= render "form", candidatura: @candidatura %>

<br>

<div>
  <%= link_to "Show this candidatura", @candidatura %> |
  <%= link_to "Back to candidaturas", candidaturas_path %>
</div>

app/views/candidaturas/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Candidaturas" %>

<h1>Candidaturas</h1>

<div id="candidaturas">
  <% @candidaturas.each do |candidatura| %>
    <%= render candidatura %>
    <p>
      <%= link_to "Show this candidatura", candidatura %>
    </p>
  <% end %>
</div>

<%= link_to "New candidatura", new_candidatura_path %>

app/views/candidaturas/new.html.erb
<% content_for :title, "New candidatura" %>

<h1>New candidatura</h1>

<%= render "form", candidatura: @candidatura %>

<br>

<div>
  <%= link_to "Back to candidaturas", candidaturas_path %>
</div>

app/views/candidaturas/selecionar_turma.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title>Urna Eletrônica</title>
   <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"> -->
   <!-- <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script> -->
    <%= stylesheet_link_tag "urna", "data-turbo-track": "reload" %>
</head>
<body>

    <div style="text-align: center">
            <img src="<%= asset_path('urna.gif') %>" alt="Banner" style="width: 100%; height: auto;"><br>
        </div>
    <div class="container text-center mt-5">
        <h1 class="mb-4">Bem-vindo(a) à Urna Eletrônica - DM</h1>
        <p class="lead">Este sistema criado para eleição dos líderes da ECIT Guarabira Dom Marcelo Pinto Carvalheira, permite realizar a eleição para líder de turma de forma prática e segura. Escolha a turma e continue para registrar seu voto. 🗳️</p>



        <div class="container mt-4">
            <h2 class="mb-3">Selecione sua Turma</h2>
            <%= form_with url: urna_candidaturas_path, method: :get do %>
                <select name="turma_id" class="form-control mb-3">
                    <option value="">Selecione...</option>
                    <% @turmas.each do |turma| %>
                        <option value="<%= turma.id %>"><%= turma.nome %></option>
                    <% end %>
                </select>
                <button type="submit" class="btn btn-primary">Continuar</button>
            <% end %>

            <% if flash[:alert] %>
                <div class="alert alert-danger mt-3">
                    <%= flash[:alert] %>
                </div>
            <% end %>
        </div>
    </div>

   <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script> -->
   <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> -->
</body>
</html>

app/views/candidaturas/show.html.erb
<p>
  <strong>Nome do Candidato:</strong>
  <%= @candidatura.nome_candidato %>
</p>

<p>
  <strong>Nome para Urna:</strong>
  <%= @candidatura.nome_urna %>
</p>

<p>
  <strong>Turma:</strong>
  <%= @candidatura.turma.nome %>
</p>

<p>
  <strong>Vice-líder:</strong>
  <%= @candidatura.vice_lider %>
</p>

<p>
  <strong>Nome para Urna do Vice:</strong>
  <%= @candidatura.nome_urna_vice %>
</p>

<p>
  <strong>Foto do Líder:</strong>
  <% if @candidatura.foto_lider.attached? %>
    <%= image_tag @candidatura.foto_lider, class: "img-thumbnail" %>
  <% else %>
    Não há foto.
  <% end %>
</p>

<p>
  <strong>Foto do Vice-líder:</strong>
  <% if @candidatura.foto_vice.attached? %>
    <%= image_tag @candidatura.foto_vice, class: "img-thumbnail" %>
  <% else %>
    Não há foto.
  <% end %>
</p>

<!-- Link para editar a candidatura -->
<p>
  <%= link_to 'Editar Candidatura', edit_candidatura_path(@candidatura), class: 'btn btn-primary' %>
</p>

app/views/candidaturas/urna.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <title>Urna Eletrônica</title>
  <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"> -->
  <%= stylesheet_link_tag "urna", "data-turbo-track": "reload" %>

  <!-- CSS do SweetAlert2 -->
  <%= stylesheet_link_tag "sweetalert2.min", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "sweetalert2.all.min", "data-turbo-track": "reload", defer: true %>


</head>
<body><br>
  <h2 class="text-center">Urna Eletrônica - Turma <%= @turma.nome %></h2>
  <mark class="text-center">
  <h3 class="text-center pulse" style=" padding: 10px; border-radius: 8px;">
    Escolha quem vai liderar a turma.
  </h3>
   <h3 class="text-center pulse" style=" padding: 10px; border-radius: 8px;">
    Ao escolher seu candidato(a), confirme seu voto! ✅
  </h3>
</mark>

  <div class="urna-container">
    <div id="visualizacao" class="text-center mb-4">
      <div class="candidato-info">
        <div id="foto-lider"></div>
        <div>
          <p id="nome-urna" class="font-weight-bold"></p>
          <p id="nome-vice"></p>
        </div>
      </div>
      <div id="mensagem-branco" class="text-center">Confirma voto em branco?</div>
    </div>

    <%= form_with url: registrar_voto_candidaturas_path, method: :post, id: "form-voto" do %>
      <%= hidden_field_tag :candidatura_id, "", id: "candidatura_id" %>
      <%= hidden_field_tag :turma_id, @turma.id %>

      <div class="candidatos-lista">
        <% @candidaturas.each do |candidato| %>
          <button type="button" class="btn btn-outline-light" onclick="selecionarCandidato('<%= candidato.id %>', '<%= candidato.nome_urna %>', '<%= candidato.nome_urna_vice %>', '<%= url_for(candidato.foto_lider) if candidato.foto_lider.attached? %>')">
            <%= candidato.nome_urna %>
            <% if candidato.nome_urna_vice.present? %>
              - <%= candidato.nome_urna_vice %>
            <% end %>
          </button>
        <% end %>
      </div>

      <div class="botoes-finais mt-4">
        <button type="button" class="btn btn-branco btn-lg" onclick="votarBranco()">BRANCO</button>
        <button type="button" class="btn btn-corrigir btn-lg" onclick="corrigirVoto()">CORRIGIR</button>
        <div id="confirmar-container">
            <button type="submit" class="btn btn-success btn-lg w-100" onclick="tocarSom(event)">CONFIRMAR</button>
        </div>
      </div>

    <% end %>
  </div>

  <script>

    function exibirBotaoConfirmar() {
        const confirmarContainer = document.getElementById("confirmar-container");
        confirmarContainer.style.display = "block";
    }

    let audio;
    document.addEventListener('DOMContentLoaded', function() {
      audio = new Audio('/teste_.wav');
      audio.preload = 'auto';
      audio.load();
    });

    function verificarAudio() {
      if (audio.paused || audio.readyState < 3) {
        audio.load();
      }
    }

    function selecionarCandidato(id, nome, nomeVice, fotoLiderUrl) {
      verificarAudio();
      document.getElementById('candidatura_id').value = id;
      document.getElementById('nome-urna').textContent = nome;
      document.getElementById('nome-vice').textContent = nomeVice ? 'Vice: ' + nomeVice : '';
      const fotoLider = document.getElementById('foto-lider');
      fotoLider.innerHTML = fotoLiderUrl ? `<img src="${fotoLiderUrl}" class="foto-candidato">` : '';
      document.getElementById('mensagem-branco').style.display = 'none';
      document.getElementById('confirmar-container').style.display = 'block';
    }

    function votarBranco() {
      verificarAudio();
      document.getElementById('candidatura_id').value = '';
      document.getElementById('nome-urna').textContent = 'Voto em Branco';
      document.getElementById('nome-vice').textContent = '';
      document.getElementById('foto-lider').innerHTML = '';
      document.getElementById('mensagem-branco').style.display = 'block';
      document.getElementById('confirmar-container').style.display = 'block';
    }

    function corrigirVoto() {
      verificarAudio();
      document.getElementById('candidatura_id').value = '';
      document.getElementById('nome-urna').textContent = '';
      document.getElementById('nome-vice').textContent = '';
      document.getElementById('foto-lider').innerHTML = '';
      document.getElementById('mensagem-branco').style.display = 'none';
      document.getElementById('confirmar-container').style.display = 'none';
    }
 function tocarSom(e) {
    e.preventDefault();
    verificarAudio();

    Swal.fire({
      title: 'Processando...',
      html: 'Por favor, aguarde.',
      allowOutsideClick: false,
      showConfirmButton: false,
      didOpen: () => { Swal.showLoading(); }
    });

    audio.currentTime = 0;
    audio.play().then(() => {
      audio.onended = () => {
        Swal.close();

        // Mostra mensagem final
        Swal.fire({
          title: 'FIM',
          html: '<h3>Voto computado com sucesso! ✅</h3>',
          icon: 'success',
          confirmButtonText: 'OK',
          allowOutsideClick: false
        }).then(() => {
          // Só segue o fluxo após o eleitor clicar em OK
          document.getElementById('form-voto').submit();
        });
      };
    }).catch(() => {
      Swal.close();
      document.getElementById('form-voto').submit();
    });
  }
  </script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Sistema Eleitoral" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/turmas/_form.html.erb
<%= form_with(model: turma) do |form| %>
  <% if turma.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(turma.errors.count, "error") %> prohibited this turma from being saved:</h2>

      <ul>
        <% turma.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/turmas/_turma.html.erb
<div id="<%= dom_id turma %>">
  <p>
    <strong>Nome:</strong>
    <%= turma.nome %>
  </p>

</div>

app/views/turmas/edit.html.erb
<% content_for :title, "Editing turma" %>

<h1>Editing turma</h1>

<%= render "form", turma: @turma %>

<br>

<div>
  <%= link_to "Show this turma", @turma %> |
  <%= link_to "Back to turmas", turmas_path %>
</div>

app/views/turmas/index.html.erb
<div class="container mt-5">
  <h1 class="text-center">Lista de Turmas</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @turmas.each do |turma| %>
        <tr>
          <td><%= turma.id %></td>
          <td><%= turma.nome %></td>
          <td>
            <%= link_to 'Mostrar', turma, class: "btn btn-primary" %>
            <%= link_to 'Editar', edit_turma_path(turma), class: "btn btn-warning" %>
            <%= link_to 'Excluir', turma, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/turmas/new.html.erb
<% content_for :title, "New turma" %>

<h1>New turma</h1>

<%= render "form", turma: @turma %>

<br>

<div>
  <%= link_to "Back to turmas", turmas_path %>
</div>

app/views/turmas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @turma %>

<div>
  <%= link_to "Edit this turma", edit_turma_path(@turma) %> |
  <%= link_to "Back to turmas", turmas_path %>

  <%= button_to "Destroy this turma", @turma, method: :delete %>
</div>